# Generated by Django 4.1.6 on 2023-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_category_options_alter_purchases_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
